### ISSUE TITLE
[java] indent +4 when wrapping inside a list literal

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#228] opened 2018-12-03 20:58 UTC
```java
class Foo {
  int[] bar() {
    return new int[]{};
  }
}
```

when pressing enter inside the {} it should indent +4

**Comment by marijnh** [comment] 2018-12-04 07:43
This seems to directly contradict some of the test cases you provided:

```
new int[] {
  0, 1, 2, 3};

new int[] {
  0, 
  1, 2, 3};

new int[] {
  0, 1, 2, 3

};
```

So are you sure about this change?

**Comment by mtaran-google** [comment] 2018-12-04 19:45
Good point. Indeed, in our codebase I find indentations of +4 and +2, so either should work fine. But right now the indent ends up being +0, which is definitely not what we'd like here.

**Comment by marijnh** [comment] 2018-12-04 21:06
That's not what I see--with matchbrackets enabled, the new empty line you get when pressing enter inside `{}` is indented two spaces more than the line above. Without matchbrackets, you won't get that empty line, and the line with the `}` will not be indented, but that's by design—since the line starts with the closing brace, it'll be dedented.

**Comment by mtaran-google** [comment] 2018-12-04 22:19
Ah, I see what's going on. You're right, my example didn't repro the issue I was seeing. Instead you can see it in

```java
class Foo {
  int[] bar() {
    return new int[]{1,2,};
  }
}
```

If you press enter after the ;, the indentation is wrong. And pressing enter after the last comma doesn't result in correct indentation (+2 or +4). Trailing commas in array literals (and enum definitions) are allowed by Java syntax: https://kariem.github.io/2016/05/04/trailing-comma-java/

**Closed** 2018-12-05 07:12 UTC
